# Generated by Django 2.2.4 on 2019-11-10 01:15

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('draft', models.BooleanField(default=False)),
                ('pub_date', models.DateTimeField(blank=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('content', ckeditor.fields.RichTextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='article_image')),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
        ),
    ]
