# Generated by Django 2.2.4 on 2019-12-13 23:10

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20191109_1715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogentry',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
