# Generated by Django 2.2.4 on 2020-01-13 01:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user_accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogauthor',
            options={},
        ),
        migrations.AlterModelManagers(
            name='blogauthor',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='blogauthor',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='blogauthor',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='blogauthor',
            name='username',
        ),
        migrations.AlterField(
            model_name='blogauthor',
            name='date_joined',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='blogauthor',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='blogauthor',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='blogauthor',
            name='is_staff',
            field=models.BooleanField(default=True),
        ),
    ]
