# Generated by Django 2.2.4 on 2020-01-13 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_accounts', '0002_auto_20200112_1754'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogauthor',
            name='alias',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
