# Generated by Django 2.2.4 on 2020-01-13 02:14

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_accounts', '0003_blogauthor_alias'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogauthor',
            old_name='alias',
            new_name='name',
        ),
        migrations.AddField(
            model_name='blogauthor',
            name='bio',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='blogauthor',
            name='prof_img',
            field=models.ImageField(blank=True, null=True, upload_to='profile_image'),
        ),
    ]
