# Generated by Django 2.2.4 on 2019-11-10 01:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Sport, PostRehab, Quality of Life, etc', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ContractionType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('cues', models.TextField()),
                ('video_id', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ExerciseDifficulty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Joint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='JointNumber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='JointType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='MovementPlane',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Muscle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='SeasonPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='workouts.Activity')),
            ],
        ),
        migrations.CreateModel(
            name='SeasonPlanDuration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('months', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Sides',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='workouts/media')),
                ('description', models.TextField(blank=True, null=True)),
                ('season_plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='season_plan', to='workouts.SeasonPlan')),
            ],
        ),
        migrations.CreateModel(
            name='WorkoutDifficulty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='WorkoutDuration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weeks', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='WorkoutFrequency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days_per_week', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='WorkoutPhase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='WorkoutType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Cardio, Met Con, Strength, Power, etc', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='WorkoutExercises',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exercise_order', models.CharField(max_length=4)),
                ('sets', models.IntegerField()),
                ('reps', models.FloatField()),
                ('rep_duration', models.BooleanField(default=False)),
                ('rest_btwn_sets_sec', models.FloatField()),
                ('intensity', models.FloatField()),
                ('intensity_percentage', models.BooleanField(default=False)),
                ('contraction_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='workouts.ContractionType')),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='workouts.Exercise')),
                ('workout_plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='workout_exercises', to='workouts.Workout')),
            ],
        ),
        migrations.AddField(
            model_name='workout',
            name='workout_difficulty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='workout_difficulty', to='workouts.WorkoutDifficulty'),
        ),
        migrations.AddField(
            model_name='workout',
            name='workout_duration',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='workout_duration', to='workouts.WorkoutDuration'),
        ),
        migrations.AddField(
            model_name='workout',
            name='workout_frequency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='workout_frequency', to='workouts.WorkoutFrequency'),
        ),
        migrations.AddField(
            model_name='workout',
            name='workout_phase',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='workout_phase', to='workouts.WorkoutPhase'),
        ),
        migrations.AddField(
            model_name='workout',
            name='workout_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='workout_type', to='workouts.WorkoutType'),
        ),
        migrations.AddField(
            model_name='seasonplan',
            name='season_duration',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='workouts.SeasonPlanDuration'),
        ),
        migrations.CreateModel(
            name='MuscleGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('muscles', models.ManyToManyField(to='workouts.Muscle')),
            ],
        ),
        migrations.CreateModel(
            name='Movement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('agonist', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='agonist_muscle', to='workouts.Muscle')),
                ('agonist_muscle_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='agonist_muscle_group', to='workouts.MuscleGroup')),
                ('antagonist', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='antagonist_muscle', to='workouts.Muscle')),
                ('joints', models.ManyToManyField(to='workouts.Joint')),
                ('movement_plane', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movement_planes', to='workouts.MovementPlane')),
                ('synergist', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='synergist_muscle', to='workouts.Muscle')),
            ],
        ),
        migrations.AddField(
            model_name='joint',
            name='joint_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='joints', to='workouts.JointType'),
        ),
        migrations.AddField(
            model_name='exercise',
            name='difficulty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='workouts.ExerciseDifficulty'),
        ),
        migrations.AddField(
            model_name='exercise',
            name='equipment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='workouts.Equipment'),
        ),
        migrations.AddField(
            model_name='exercise',
            name='joint_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='workouts.JointNumber'),
        ),
        migrations.AddField(
            model_name='exercise',
            name='movements',
            field=models.ManyToManyField(to='workouts.Movement'),
        ),
        migrations.AddField(
            model_name='exercise',
            name='sides',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='workouts.Sides'),
        ),
    ]
