# Generated by Django 2.2.4 on 2019-08-23 07:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ContractionType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('cues', models.TextField()),
                ('video', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='ExerciseDifficulty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Joint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='JointNumber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='JointType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='MovementPlane',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Muscle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='SeasonPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='workouts.Activity')),
            ],
        ),
        migrations.CreateModel(
            name='SeasonPlanDuration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season_duration', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Sides',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('season_plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='workouts.SeasonPlan')),
            ],
        ),
        migrations.CreateModel(
            name='WorkoutDifficulty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='WorkoutDuration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weeks', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='WorkoutFrequency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days_per_week', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='WorkoutPhase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='WorkoutType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='WorkoutExercises',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sets', models.IntegerField()),
                ('reps', models.FloatField()),
                ('rep_duration', models.BooleanField(default=False)),
                ('rest_btwn_sets_sec', models.FloatField()),
                ('intensity', models.FloatField()),
                ('intensity_percentage', models.BooleanField(default=False)),
                ('contraction_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='workouts.ContractionType')),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='workouts.Exercise')),
                ('workout_plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='workouts.Workout')),
            ],
        ),
        migrations.AddField(
            model_name='workout',
            name='workout_difficulty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='workouts.WorkoutDifficulty'),
        ),
        migrations.AddField(
            model_name='workout',
            name='workout_duration',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='workouts.WorkoutDuration'),
        ),
        migrations.AddField(
            model_name='workout',
            name='workout_frequency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='workouts.WorkoutFrequency'),
        ),
        migrations.AddField(
            model_name='workout',
            name='workout_phase',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='workouts.WorkoutPhase'),
        ),
        migrations.AddField(
            model_name='workout',
            name='workout_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='workouts.WorkoutType'),
        ),
        migrations.AddField(
            model_name='seasonplan',
            name='season_duration',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='workouts.SeasonPlanDuration'),
        ),
        migrations.CreateModel(
            name='MuscleGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('muscle_1', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='muscle_1', to='workouts.Muscle')),
                ('muscle_10', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='muscle_10', to='workouts.Muscle')),
                ('muscle_2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='muscle_2', to='workouts.Muscle')),
                ('muscle_3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='muscle_3', to='workouts.Muscle')),
                ('muscle_4', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='muscle_4', to='workouts.Muscle')),
                ('muscle_5', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='muscle_5', to='workouts.Muscle')),
                ('muscle_6', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='muscle_6', to='workouts.Muscle')),
                ('muscle_7', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='muscle_7', to='workouts.Muscle')),
                ('muscle_8', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='muscle_8', to='workouts.Muscle')),
                ('muscle_9', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='muscle_9', to='workouts.Muscle')),
            ],
        ),
        migrations.CreateModel(
            name='Movement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('agonist', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='agonist_muscle', to='workouts.Muscle')),
                ('agonist_muscle_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='agonist_muscle_group', to='workouts.MuscleGroup')),
                ('antagonist', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='antagonist_muscle', to='workouts.Muscle')),
                ('joint_1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='joint_1', to='workouts.Joint')),
                ('joint_2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='joint_2', to='workouts.Joint')),
                ('movement_plane', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='workouts.MovementPlane')),
                ('synergist', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='synergist_muscle', to='workouts.Muscle')),
            ],
        ),
        migrations.AddField(
            model_name='joint',
            name='joint_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='workouts.JointType'),
        ),
        migrations.AddField(
            model_name='exercise',
            name='difficulty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='workouts.ExerciseDifficulty'),
        ),
        migrations.AddField(
            model_name='exercise',
            name='equipment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='workouts.Equipment'),
        ),
        migrations.AddField(
            model_name='exercise',
            name='joint_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='workouts.JointNumber'),
        ),
        migrations.AddField(
            model_name='exercise',
            name='movement_1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movement_1', to='workouts.Movement'),
        ),
        migrations.AddField(
            model_name='exercise',
            name='movement_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movement_2', to='workouts.Movement'),
        ),
        migrations.AddField(
            model_name='exercise',
            name='movement_3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movement_3', to='workouts.Movement'),
        ),
        migrations.AddField(
            model_name='exercise',
            name='sides',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='workouts.Sides'),
        ),
    ]
