# Generated by Django 2.2.4 on 2019-08-23 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0003_auto_20190823_1805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='name',
            field=models.CharField(help_text='Sport, PostRehab, Quality of Life, etc', max_length=100),
        ),
        migrations.AlterField(
            model_name='contractiontype',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='video',
            field=models.URLField(max_length=255),
        ),
        migrations.AlterField(
            model_name='exercisedifficulty',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='joint',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='jointtype',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='movementplane',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='sides',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='workouttype',
            name='name',
            field=models.CharField(help_text='Cardio, Met Con, Strength, Power, etc', max_length=100),
        ),
    ]
