# Generated by Django 2.2.4 on 2019-08-23 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0004_auto_20190823_1844'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='musclegroup',
            name='muscle_1',
        ),
        migrations.RemoveField(
            model_name='musclegroup',
            name='muscle_10',
        ),
        migrations.RemoveField(
            model_name='musclegroup',
            name='muscle_2',
        ),
        migrations.RemoveField(
            model_name='musclegroup',
            name='muscle_3',
        ),
        migrations.RemoveField(
            model_name='musclegroup',
            name='muscle_4',
        ),
        migrations.RemoveField(
            model_name='musclegroup',
            name='muscle_5',
        ),
        migrations.RemoveField(
            model_name='musclegroup',
            name='muscle_6',
        ),
        migrations.RemoveField(
            model_name='musclegroup',
            name='muscle_7',
        ),
        migrations.RemoveField(
            model_name='musclegroup',
            name='muscle_8',
        ),
        migrations.RemoveField(
            model_name='musclegroup',
            name='muscle_9',
        ),
        migrations.AddField(
            model_name='musclegroup',
            name='muscles',
            field=models.ManyToManyField(to='workouts.Muscle'),
        ),
    ]
