# Generated by Django 2.2.4 on 2019-08-23 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0005_auto_20190823_2249'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercise',
            name='movement_1',
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='movement_2',
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='movement_3',
        ),
        migrations.RemoveField(
            model_name='movement',
            name='joint_1',
        ),
        migrations.RemoveField(
            model_name='movement',
            name='joint_2',
        ),
        migrations.AddField(
            model_name='exercise',
            name='movements',
            field=models.ManyToManyField(to='workouts.Movement'),
        ),
        migrations.AddField(
            model_name='movement',
            name='joints',
            field=models.ManyToManyField(to='workouts.Joint'),
        ),
    ]
